#
#   Simple extension of CC7 with GridFTP and gsissh
#
#..................................................................
FROM cern/cc7-base:latest

RUN yum install -y globus-ftp-client gsissh gsi-openssh-clients
